### ISSUE TITLE
New language select error

### ISSUE THREAD

**Issue by csbalazs** [ITPrism/ITPTransifex#1]
If I add a new language to ITP Transifex then I can not select this one in Package options.

Joomla! 3.4.1
ITP Transifex 1.6 Lite
ITPrism Library Version 1.21

**Comment by ITPrism** [comment]
Hi,
Thank you for the post!

Could you attach screenshot, please?

**Comment by csbalazs** [comment]
![20150508](https://cloud.githubusercontent.com/assets/1657924/7532923/b9de0c2c-f56c-11e4-9f9e-df2be8475a76.png)

**Comment by ITPrism** [comment]
Hi,
I see. So, you have to enter language code there. 
For example **de_DE**.

That is not drop down where you will be able to select a language.
Hmm...It will be better to do it a drop down for next release.

B/R

**Comment by csbalazs** [comment]
Hm...I was looking for drop down list, because i found this one in the guide.
http://itprism.com/help/117-transifex-language-manager-guide#packages
![201505082](https://cloud.githubusercontent.com/assets/1657924/7534618/85238420-f57c-11e4-8773-16dfc26a63ee.png)

**Comment by csbalazs** [comment]
Drop down list is a good idea.

**Comment by ITPrism** [comment]
Fixed in [ITP Transifex] (http://itprism.com/free-joomla-extensions/others/language-packages-manager)  version 2.0
