### ISSUE TITLE
Tooltips doesn't appear

### ISSUE THREAD

**Issue by csbalazs** [ITPrism/ITPTransifex#2]
![201505084](https://cloud.githubusercontent.com/assets/1657924/7534710/5ba1b594-f57d-11e4-9e28-c3b5bb80f6a7.png)

and missing Language string's value

Joomla! 3.4.1
ITP Transifex 1.6 Lite
ITPrism Library Version 1.21

**Comment by ITPrism** [comment]
Fixed in [ITP Transifex] (http://itprism.com/free-joomla-extensions/others/language-packages-manager)  version 2.0
