### ISSUE TITLE
Project image upload error

### ISSUE THREAD

**Issue by csbalazs** [ITPrism/ITPTransifex#3]
The uploaded projects picture doesn't appear.

![image](https://cloud.githubusercontent.com/assets/1657924/7798636/792ea112-02fc-11e5-9837-c70889d3c246.png)

**Comment by csbalazs** [comment]
Update: The installer can not create the default media folder (images/itptransifex).

**Comment by ITPrism** [comment]
I am not sure, but it works on my server.
I guess, it is missing the folder **images/itptransifex**. Create it manually.

Test [ITP Transifex] (http://itprism.com/free-joomla-extensions/others/language-packages-manager) v2.0
