### ISSUE TITLE
Installerscript target

### ISSUE THREAD

**Issue by PierreCorell** [ITPrism/ITPTransifex#4]
Hey there,

for installing languages into Joomla: languages should be located into language/XY-XY, not into /component/NAME/language/XY-XY
independent of type component, plugin, module etc.

Same at admin structure. Please check and correct it.
Thanks.

**Comment by ITPrism** [comment]
Hi Pierre,
Thank you for the post!
The language file can be stored in back-end and front-end extension folder.
Check this out.

https://docs.joomla.org/Specification_of_language_files
https://docs.joomla.org/Manifest_files#Language_files

It was mentioned, the language folders will be deprecated, so I did it to store language files in extensions folders.

http://osdir.com/ml/joomla/2013-03/msg00252.html

It works well now and it is not necessary to change it.
However, there are some specific things that must be met to work correctly ITP Transifex, when creating resources in Transifex.
I will describe them in the documentation in the coming days.

**Comment by PierreCorell** [comment]
Hi Todor,
thanks for the advice. I did not know this.

I will have a look on other extensions, because the first extension for which I used your component, did not load the languages from its own folders, the front- and backend languages were still english. After changing the xml it worked as expected.

Alright, I see now that the extension developers should better follow the encourage to retrieve languages from the components etc. folders.
I will write a notice for the extensions developers which do not follow this recommendation if I find more of them - I plan to use your extension more often now. It works great so far :-)

Best regards, Pierre.

**Comment by ITPrism** [comment]
Hi Pierre,
I hope my extensions to be useful for you. :)

I published new version of [ITP Transifex v2.1] (http://itprism.com/free-joomla-extensions/others/language-packages-manager).
I added option to select where the system has to store the files.

Cheers,
Todor
