### ISSUE TITLE
Package type is too complicated

### ISSUE THREAD

**Issue by csbalazs** [ITPrism/ITPTransifex#5]
I translated Gantry5 framework to Hungarian laguage. The Gantry5 package have component, modules, plugin, library, and other (tpl. pkg, files) types, than I can not create own language package, because this structure is too complicated in ITPTransifex. I think, it would be better, if I do not need to choose a type, but also just a folder (root/administrator/languages or root/languages).
![image](https://cloud.githubusercontent.com/assets/1657924/10111122/0f03fa30-63d2-11e5-857b-06cc2313df28.png)

I have files, pkg, etc types.
![image](https://cloud.githubusercontent.com/assets/1657924/10111148/4a72a0b2-63d2-11e5-92a8-9025307ad7cc.png)

**Comment by ITPrism** [comment]
Hi,
Thank you for the post!

Hmm...You are right. It will be better if it is possible to enter folder where have to be stored the files.
I will think about that and I can do that as version 3.0

You can select "Language Folders" for option "Files location" in the component options, tab "Advanced".

![options](https://cloud.githubusercontent.com/assets/1272206/10112481/3ac6fffc-63e4-11e5-8bac-850359cf4ed4.png)

**Comment by csbalazs** [comment]
Thx!
